import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';

test('Admin V4 has a real V4 entry point instead of the old V2 mainframe name', () => {
  const appSource = readFileSync('src/App.tsx', 'utf8');
  const adminSource = readFileSync('src/views/AdminV4View.tsx', 'utf8');
  const cacheSource = readFileSync('src/utils/adminV4Cache.ts', 'utf8');
  const formatSource = readFileSync('src/utils/adminV4Format.ts', 'utf8');
  const matchUtilsSource = readFileSync('src/utils/adminV4MatchUtils.ts', 'utf8');
  const pickListStateSource = readFileSync('src/utils/adminV4PickListState.ts', 'utf8');
  const actionHookSource = readFileSync('src/components/adminv4/useAdminV4ActionConfirmation.ts', 'utf8');
  const scrollHookSource = readFileSync('src/components/adminv4/useAdminV4ScrollMemory.ts', 'utf8');
  const scoutRewardsHookSource = readFileSync('src/components/adminv4/useAdminV4ScoutRewards.ts', 'utf8');
  const scoutIdentityHookSource = readFileSync('src/components/adminv4/useAdminV4ScoutIdentitySettings.ts', 'utf8');
  const manualSimulatorHookSource = readFileSync('src/components/adminv4/useAdminV4ManualSimulator.ts', 'utf8');
  const workbookSheetsSource = readFileSync('src/utils/adminV4WorkbookSheets.ts', 'utf8');

  assert.ok(existsSync('src/views/AdminV4View.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4SimulatorTables.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4ScoutStaffingPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4SourceFreshnessPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4ScoutRewardsPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4SettingsModal.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4ReportsPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4ImportsPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4CommandPalette.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4PreScoutPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4BackupSyncPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4RawAuditPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4ModelValidationPanel.tsx'));
  assert.ok(existsSync('src/components/adminv4/AdminV4ChartTypes.ts'));
  assert.ok(existsSync('src/components/adminv4/AdminV4RiskPill.ts'));
  assert.ok(existsSync('src/components/adminv4/useAdminV4ActionConfirmation.ts'));
  assert.ok(existsSync('src/components/adminv4/useAdminV4ScrollMemory.ts'));
  assert.ok(existsSync('src/components/adminv4/useAdminV4ScoutRewards.ts'));
  assert.ok(existsSync('src/components/adminv4/useAdminV4ScoutIdentitySettings.ts'));
  assert.ok(existsSync('src/components/adminv4/useAdminV4ManualSimulator.ts'));
  assert.ok(existsSync('src/utils/adminV4Cache.ts'));
  assert.ok(existsSync('src/utils/adminV4Format.ts'));
  assert.ok(existsSync('src/utils/adminV4MatchUtils.ts'));
  assert.ok(existsSync('src/utils/adminV4PickListState.ts'));
  assert.ok(existsSync('src/utils/adminV4WorkbookSheets.ts'));
  assert.equal(existsSync('src/views/AdminMainframeV2View.tsx'), false);
  assert.match(appSource, /import\('\.\/views\/AdminV4View'\)/);
  assert.doesNotMatch(appSource, /AdminMainframeV2View/);
  assert.match(cacheSource, /loadLatestCachedPayload/);
  assert.match(cacheSource, /isCachedTbaMatches/);
  assert.match(formatSource, /formatAdminV4MetricValue/);
  assert.match(formatSource, /parseAdminV4QuickTeamEntry/);
  assert.match(matchUtilsSource, /getAdminV4PlayedMatchWinner/);
  assert.match(matchUtilsSource, /mergeAdminV4V3WithLegacyRows/);
  assert.match(pickListStateSource, /loadAdminV4PickListState/);
  assert.match(actionHookSource, /useAdminV4ActionConfirmation/);
  assert.match(actionHookSource, /requestActionConfirmation/);
  assert.match(actionHookSource, /requestRef/);
  assert.match(scrollHookSource, /useAdminV4ScrollMemory/);
  assert.match(scrollHookSource, /createScrollSnapshot/);
  assert.match(scrollHookSource, /viewScrollPositionsRef/);
  assert.match(scoutRewardsHookSource, /useAdminV4ScoutRewards/);
  assert.match(scoutRewardsHookSource, /settlePowerCoinBetsForMatch/);
  assert.match(scoutRewardsHookSource, /DEFAULT_ADMIN_V4_SCOUTS/);
  assert.match(scoutRewardsHookSource, /optimizeScoutAssignments/);
  assert.match(scoutRewardsHookSource, /downloadCsvFile/);
  assert.match(scoutIdentityHookSource, /useAdminV4ScoutIdentitySettings/);
  assert.match(scoutIdentityHookSource, /saveScoutIdentityAdminSecret/);
  assert.match(scoutIdentityHookSource, /loadScoutIdentityAdminSecret/);
  assert.match(manualSimulatorHookSource, /useAdminV4ManualSimulator/);
  assert.match(manualSimulatorHookSource, /parseAdminV4QuickTeamEntry/);
  assert.match(manualSimulatorHookSource, /parseAdminV4TeamNumbers/);
  assert.match(manualSimulatorHookSource, /buildSimulatorRow/);
  assert.match(manualSimulatorHookSource, /summarizePpaAlliance/);
  assert.match(workbookSheetsSource, /addWorkbookSheet/);
  assert.match(workbookSheetsSource, /addQualificationProjectionSheet/);
  assert.match(workbookSheetsSource, /addQualPredictionSheet/);
  assert.match(workbookSheetsSource, /addFinalsProjectionSheet/);
  assert.match(adminSource, /useAdminV4ActionConfirmation/);
  assert.match(adminSource, /useAdminV4ScrollMemory/);
  assert.match(adminSource, /useAdminV4ScoutRewards/);
  assert.match(adminSource, /useAdminV4ScoutIdentitySettings/);
  assert.match(adminSource, /useAdminV4ManualSimulator/);
  assert.match(pickListStateSource, /normalizeAdminV4PickStatusMap/);
  assert.doesNotMatch(adminSource, /const getLatestAdminV4CachePayload/);
  assert.doesNotMatch(adminSource, /const isCachedTbaMatches/);
  assert.doesNotMatch(adminSource, /const formatMetricValue/);
  assert.doesNotMatch(adminSource, /const parseQuickTeamEntry/);
  assert.doesNotMatch(adminSource, /const isPlayedMatch/);
  assert.doesNotMatch(adminSource, /const mergeV3WithLegacyRows/);
  assert.doesNotMatch(adminSource, /const getAdminV4PickListStorageKey/);
  assert.doesNotMatch(adminSource, /settlePowerCoinBetsForMatch/);
  assert.doesNotMatch(adminSource, /const getOpenPowerCoinImpact/);
  assert.doesNotMatch(adminSource, /const handleOptimizeScouts/);
  assert.doesNotMatch(adminSource, /downloadCsvFile/);
  assert.doesNotMatch(adminSource, /scoutIdentityBackendLoaded/);
  assert.doesNotMatch(adminSource, /saveScoutIdentityAdminSecret/);
  assert.doesNotMatch(adminSource, /parseAdminV4QuickTeamEntry as parseQuickTeamEntry/);
  assert.doesNotMatch(adminSource, /parseAdminV4TeamNumbers as parseManualTeamNumbers/);
  assert.doesNotMatch(adminSource, /const buildSimulatorRow/);
  assert.doesNotMatch(adminSource, /simulatorDefenseImpactLookup/);
  assert.doesNotMatch(adminSource, /type WorkbookColumn/);
  assert.doesNotMatch(adminSource, /const styleWorkbookHeader/);
});

test('Admin V4 scout assignment optimizer plans for same-team continuity across the schedule', () => {
  const strategyBrainSource = readFileSync('src/utils/strategyBrain.ts', 'utf8');
  const staffingSource = readFileSync('src/components/adminv4/AdminV4ScoutStaffingPanel.tsx', 'utf8');
  const scoutRewardsHookSource = readFileSync('src/components/adminv4/useAdminV4ScoutRewards.ts', 'utf8');

  assert.match(strategyBrainSource, /const slotsByTeam = new Map/);
  assert.match(strategyBrainSource, /chooseBatchScout/);
  assert.match(strategyBrainSource, /continuityGain \* 450/);
  assert.match(strategyBrainSource, /rebalanceLoads/);
  assert.match(strategyBrainSource, /improveContinuityWithSwaps/);
  assert.match(strategyBrainSource, /Team continuity optimization/);
  assert.doesNotMatch(strategyBrainSource, /Repeated exposure optimization/);
  assert.match(staffingSource, /whole schedule/);
  assert.match(staffingSource, /same-team continuity/);
  assert.match(staffingSource, /Optimize Schedule/);
  assert.match(scoutRewardsHookSource, /repeated scout-team pairing/);
});

test('Admin V4 keeps expert controls behind task-focused workflow surfaces', () => {
  const adminSource = readFileSync('src/views/AdminV4View.tsx', 'utf8');
  const commandBarSource = readFileSync('src/components/adminv4/AdminV4CommandBar.tsx', 'utf8');
  const commandPaletteSource = readFileSync('src/components/adminv4/AdminV4CommandPalette.tsx', 'utf8');
  const nowSource = readFileSync('src/components/adminv4/AdminV4NowWorkflow.tsx', 'utf8');
  const teamSearchSource = readFileSync('src/utils/adminV4TeamSearch.ts', 'utf8');
  const smartSearchSource = readFileSync('src/utils/adminV4SmartSearch.ts', 'utf8');
  const primitivesSource = readFileSync('src/components/adminv4/AdminV4Primitives.tsx', 'utf8');
  const matchesSource = readFileSync('src/components/adminv4/AdminV4MatchesWorkflow.tsx', 'utf8');
  const manualSimulatorSource = readFileSync('src/components/adminv4/AdminV4ManualSimulatorPanel.tsx', 'utf8');
  const pickListSource = readFileSync('src/components/adminv4/AdminV4PickListWorkflow.tsx', 'utf8');
  const teamsSource = readFileSync('src/components/adminv4/AdminV4TeamsWorkflow.tsx', 'utf8');
  const statControlsSource = readFileSync('src/components/adminv4/AdminV4StatControls.tsx', 'utf8');
  const dataOverviewSource = readFileSync('src/components/adminv4/AdminV4DataOverviewWorkflow.tsx', 'utf8');
  const dataPipelineSource = readFileSync('src/components/adminv4/AdminV4DataPipelinePanel.tsx', 'utf8');
  const strategyPanelSource = readFileSync('src/components/adminv4/AdminV4StrategyPlanPanel.tsx', 'utf8');
  const teamEvidenceSource = readFileSync('src/components/adminv4/AdminV4TeamEvidencePanels.tsx', 'utf8');
  const visualizeSource = readFileSync('src/components/adminv4/AdminV4VisualizeWorkflow.tsx', 'utf8');
  const staffingSource = readFileSync('src/components/adminv4/AdminV4ScoutStaffingPanel.tsx', 'utf8');
  const sourceFreshnessSource = readFileSync('src/components/adminv4/AdminV4SourceFreshnessPanel.tsx', 'utf8');
  const scrollHookSource = readFileSync('src/components/adminv4/useAdminV4ScrollMemory.ts', 'utf8');
  const reportsPanelSource = readFileSync('src/components/adminv4/AdminV4ReportsPanel.tsx', 'utf8');
  const importsPanelSource = readFileSync('src/components/adminv4/AdminV4ImportsPanel.tsx', 'utf8');
  const preScoutPanelSource = readFileSync('src/components/adminv4/AdminV4PreScoutPanel.tsx', 'utf8');
  const reportsSource = readFileSync('src/components/adminv4/AdminV4ReportsWorkflow.tsx', 'utf8');
  const modelValidationSource = readFileSync('src/components/adminv4/AdminV4ModelValidationPanel.tsx', 'utf8');
  const workflowSource = readFileSync('src/utils/scoutingWorkflow.ts', 'utf8');
  const strategyCopySource = readFileSync('src/utils/adminV4StrategyCopy.ts', 'utf8');
  const formatSource = readFileSync('src/utils/adminV4Format.ts', 'utf8');
  const ppaSource = readFileSync('src/utils/ppaInsights.ts', 'utf8');
  const guardSource = readFileSync('src/components/admin/AdminGuard.tsx', 'utf8');
  const cssSource = readFileSync('src/index.css', 'utf8');

  ['Now', 'Teams', 'Matches', 'Pick List', 'Visualize', 'Data', 'Reports'].forEach(label => {
    assert.match(adminSource, new RegExp(`label: '${label}'`));
  });
  assert.doesNotMatch(adminSource, /label: 'Match Now'/);
  assert.doesNotMatch(adminSource, /label: 'Collect Missing Data'/);
  assert.doesNotMatch(adminSource, /label: 'Data Health'/);
  assert.match(nowSource, /Next Best Action/);
  assert.match(nowSource, /Other Useful Actions/);
  assert.match(nowSource, /Competition Phase/);
  assert.match(nowSource, /Select the day we are operating in/);
  assert.match(nowSource, /Fast Situation Switches/);
  assert.match(nowSource, /Start with the problem, not the tab name/);
  assert.match(nowSource, /aria-label="Competition phase selector"/);
  assert.match(nowSource, /aria-label="Competition need launcher"/);
  assert.match(nowSource, /aria-label=\{`Competition mode: \$\{need\.label\}\. \$\{need\.detail\}`\}/);
  assert.match(nowSource, /Phone Shortcuts/);
  assert.match(nowSource, /Tap the match-day job, not the tab name/);
  assert.match(nowSource, /\[primaryAction, \.\.\.secondaryActions\]\.slice\(0, 4\)/);
  assert.match(nowSource, /aria-label=\{`Open phone shortcut: \$\{action\.label\}\. \$\{action\.detail\}`\}/);
  assert.match(nowSource, /mt-5 hidden gap-4 md:grid xl:grid-cols-\[minmax\(0,1fr\)_360px\]/);
  assert.match(nowSource, /aria-label="Other useful match-day actions"/);
  assert.match(nowSource, /secondaryActions\.length === 0/);
  assert.doesNotMatch(nowSource, /<summary[^>]*>\s*Other Useful Actions/);
  assert.match(nowSource, /Open Match Plan Details/);
  assert.match(nowSource, /admin-details-body/);
  assert.match(nowSource, /onKeyDown=\{event =>/);
  assert.match(nowSource, /One match-day command surface/);
  assert.match(nowSource, /Secondary details are collapsed/);
  assert.match(adminSource, /Open Match Plan/);
  assert.match(adminSource, /label: 'Match soon'/);
  assert.match(adminSource, /label: 'Data looks wrong'/);
  assert.match(adminSource, /label: 'Prediction checkpoint'/);
  assert.match(adminSource, /actionLabel: 'Save snapshot'/);
  assert.match(adminSource, /future forecasts are ready to timestamp/);
  assert.match(adminSource, /label: 'Assign scouts'/);
  assert.match(adminSource, /label: 'Alliance selection'/);
  assert.match(adminSource, /label: 'Demo proof'/);
  assert.match(adminSource, /Scout Tasks/);
  assert.match(adminSource, /Collect missing evidence/);
  assert.match(adminSource, /Assign Evidence Tasks/);
  assert.match(adminSource, /Local Avg/);
  assert.match(adminSource, /Advanced public ratings/);
  assert.match(adminSource, /admin-details-body mt-3 space-y-2/);
  assert.match(adminSource, /title: 'Official Avg'/);
  assert.match(adminSource, /title: 'Public Rating'/);
  assert.match(adminSource, /title: 'Defense Against'/);
  assert.doesNotMatch(adminSource, /Open Full Plan/);
  assert.doesNotMatch(adminSource, /Scout Dispatch/);
  assert.doesNotMatch(adminSource, /Fill Evidence Gaps/);
  assert.doesNotMatch(adminSource, /SummaryCard label="PPC"/);
  assert.doesNotMatch(adminSource, /title: 'PPC'/);
  assert.doesNotMatch(adminSource, /title: 'OPR'/);
  assert.doesNotMatch(adminSource, /title: 'DPR'/);
  assert.doesNotMatch(adminSource, /Current model:/);
  assert.doesNotMatch(adminSource, /The strongest local input for PPC/);
  assert.match(adminSource, /Load Team Data First/);
  assert.match(adminSource, /Load Schedule First/);
  assert.match(adminSource, /Official Sources/);
  assert.match(adminSource, /Official Source Needed/);
  assert.match(adminSource, /schedule\/source missing/);
  assert.match(adminSource, /No official source loaded/);
  assert.match(adminSource, /Scout Evidence/);
  assert.match(adminSource, /public-only context/);
  assert.doesNotMatch(adminSource, /public\/model fallback|offline fallbacks|fallback-compatible metric|model fallback|Public fallback context|schedule fallback|flat schedule fallback/);
  assert.match(adminSource, /uploaded schedule/);
  assert.match(adminSource, /Ranges Ready/);
  assert.match(adminSource, /Needs Local Rows/);
  assert.match(adminSource, /Needs role evidence/);
  assert.match(adminSource, /Needs official rankings/);
  assert.match(formatSource, /No source timestamp/);
  assert.doesNotMatch(adminSource, /PPA Pending/);
  assert.doesNotMatch(adminSource, /Fallback Only/);
  assert.doesNotMatch(adminSource, /No Cache Yet/);
  assert.doesNotMatch(adminSource, /Official source cache is missing|official schedule\/source cache is missing|No source cache|schedule\/cache missing|No cached sources/);
  assert.doesNotMatch(ppaSource, /No PPA rating is available/);
  assert.doesNotMatch(ppaSource, /Public\/model fallback only|Unknown floor|label: 'Unknown'/);
  assert.match(ppaSource, /Needs local scout rows/);
  assert.match(ppaSource, /Needs Role Evidence/);
  assert.match(ppaSource, /Floor needs evidence/);
  assert.match(adminSource, /primaryWorkflowItemIds = \['command', 'sorter', 'predictor', 'pickList', 'visualize', 'data', 'export'\]/);
  assert.match(commandBarSource, /activePanel/);
  assert.match(commandBarSource, /onOpenWorkflowItem/);
  assert.match(matchesSource, /Automatic Future Match Simulations/);
  assert.match(matchesSource, /Manual simulator is reserved for custom what-if alliances/);
  assert.match(matchesSource, /onKeyDown=\{event =>/);
  assert.match(manualSimulatorSource, /onBack: \(\) => void/);
  assert.match(manualSimulatorSource, /Back to Matches/);
  assert.match(adminSource, /onBack=\{\(\) => openWorkflow\('predictor'\)\}/);
  assert.doesNotMatch(adminSource, /Load Into Manual Simulator/);
  assert.match(teamEvidenceSource, /What this team still needs/);
  assert.match(teamsSource, /Metric Guide/);
  assert.match(teamsSource, /Right click or press the info button for metric info/);
  assert.match(teamsSource, /aria-label=\{`Get info for \$\{label\}`\}/);
  assert.match(teamsSource, /event\.stopPropagation\(\)/);
  assert.match(teamsSource, /onInfo=\{onOpenWiki\}/);
  assert.match(teamsSource, /basicTeamSortFields/);
  assert.match(teamsSource, /visibleSortOptions/);
  assert.match(teamsSource, /onKeyDown=\{event =>/);
  assert.match(teamsSource, /Local Avg/);
  assert.match(teamsSource, /Official Avg/);
  assert.match(teamsSource, /Public Rating/);
  assert.match(teamsSource, /Needs official rankings/);
  assert.doesNotMatch(teamsSource, /SortableHeader label="PPC"/);
  assert.doesNotMatch(teamsSource, /SortableHeader label="OPR"/);
  assert.doesNotMatch(teamsSource, /SortableHeader label="DPR"/);
  assert.doesNotMatch(teamsSource, /aria-label=\{`Explain \$\{label\}`\}/);
  assert.match(teamsSource, /Low Scout Trust/);
  assert.match(teamsSource, /Expected value/);
  assert.doesNotMatch(adminSource, /<table className="admin-sticky-table min-w-\\[420px\\]/);
  assert.doesNotMatch(adminSource, /Every known future match is simulated here first/);
  assert.match(adminSource, /AdminV4PickListWorkflow/);
  assert.match(adminSource, /AdminV4RawAuditPanel/);
  assert.match(adminSource, /AdminV4ModelValidationPanel/);
  assert.match(adminSource, /AdminV4ScoutStaffingPanel/);
  assert.match(adminSource, /AdminV4SourceFreshnessPanel/);
  assert.match(adminSource, /AdminV4ReportsPanel/);
  assert.match(adminSource, /AdminV4ImportsPanel/);
  assert.match(adminSource, /AdminV4PreScoutPanel/);
  assert.match(adminSource, /Trust Calibration/);
  assert.match(adminSource, /Model Inputs/);
  assert.match(adminSource, /Before-Match Inputs/);
  assert.doesNotMatch(adminSource, /title="Raw Data Audit"/);
  assert.doesNotMatch(adminSource, /Official source cache is empty/);
  assert.doesNotMatch(adminSource, /Drive Team Packet/);
  assert.doesNotMatch(adminSource, /TBA Data Import/);
  assert.doesNotMatch(adminSource, /Returned Pre Scout evidence is included/);
  assert.doesNotMatch(adminSource, /Reference Model/);
  assert.doesNotMatch(adminSource, /Pre-Match Feature Matrix/);
  assert.doesNotMatch(adminSource, /Model Calibration|Model Features|Pre-Match Features/);
  assert.doesNotMatch(adminSource, /Scout Assignment Optimizer/);
  assert.doesNotMatch(adminSource, /Assignment Sheet/);
  assert.match(modelValidationSource, /function AdminV4ModelValidationPanel/);
  assert.match(modelValidationSource, /Model Trust/);
  assert.match(modelValidationSource, /local avg/);
  assert.doesNotMatch(modelValidationSource, /PPC \$\{/);
  assert.match(modelValidationSource, /Baseline For Comparison/);
  assert.match(modelValidationSource, /What Was Known Before Matches/);
  assert.doesNotMatch(modelValidationSource, /Reference Model/);
  assert.doesNotMatch(modelValidationSource, /Pre-Match Feature Matrix/);
  assert.match(pickListSource, /Meeting Mode/);
  assert.match(pickListSource, /Full Live Board/);
  assert.match(pickListSource, /Undo Status/);
  assert.match(pickListSource, /Status Menu/);
  assert.match(pickListSource, /Live Pick Status Entry/);
  assert.match(pickListSource, /onQuickStatusChange/);
  assert.match(pickListSource, /Uses the same confirm and undo path as row status menus/);
  assert.match(pickListSource, /Picked by, e\.g\. A3/);
  assert.match(pickListSource, /applyQuickStatus\('picked', ownAllianceLabel\)/);
  assert.match(pickListSource, /applyQuickStatus\('declined'\)/);
  assert.match(pickListSource, /Status change canceled/);
  assert.match(adminSource, /handleQuickPickStatusChange/);
  assert.match(adminSource, /return false/);
  assert.match(pickListSource, /pickListMeetingMode \? \(/);
  assert.match(dataPipelineSource, /Collection Pipeline/);
  assert.match(dataPipelineSource, /SCOUTING_USE_MOMENTS/);
  assert.match(dataOverviewSource, /AdminV4DataQuickNeed/);
  assert.match(dataOverviewSource, /During Competition/);
  assert.match(dataOverviewSource, /Say the problem, not the panel name/);
  assert.doesNotMatch(dataOverviewSource, /If You Need\.\.\./);
  assert.doesNotMatch(dataOverviewSource, /Plain-language maintenance shortcuts/);
  assert.match(dataOverviewSource, /These are the emergency doors for a loud pit or stands moment/);
  assert.match(dataOverviewSource, /I need to/);
  assert.match(adminSource, /dataQuickNeeds/);
  assert.match(adminSource, /load schedule or rankings/);
  assert.match(adminSource, /assign scouts for the next block/);
  assert.match(adminSource, /fix missing or suspicious rows/);
  assert.match(adminSource, /prove the model is safe to trust/);
  assert.match(adminSource, /sync or back up this device/);
  assert.match(adminSource, /Load Schedule \/ Rankings/);
  assert.match(adminSource, /Collect Scout Evidence/);
  assert.match(adminSource, /Fix Missing \/ Bad Rows/);
  assert.match(adminSource, /Sync \/ Backup Device/);
  assert.match(dataOverviewSource, /All Data Tools/);
  assert.match(dataOverviewSource, /<details/);
  assert.match(dataOverviewSource, /admin-details-body/);
  assert.match(strategyPanelSource, /function AdminV4StrategyPlanPanel/);
  assert.match(staffingSource, /function AdminV4ScoutStaffingPanel/);
  assert.match(staffingSource, /Scout Assignment Builder/);
  assert.match(staffingSource, /Station Plan/);
  assert.doesNotMatch(staffingSource, /Scout Assignment Optimizer/);
  assert.doesNotMatch(staffingSource, /Assignment Sheet/);
  assert.match(sourceFreshnessSource, /function AdminV4SourceFreshnessPanel/);
  assert.match(sourceFreshnessSource, /Official schedule\/source missing/);
  assert.match(reportsPanelSource, /function AdminV4ReportsPanel/);
  assert.match(reportsPanelSource, /Drive Team Packet/);
  assert.match(reportsPanelSource, /Raw Evidence And Backup/);
  assert.match(reportsPanelSource, /Trust Calibration/);
  assert.match(reportsPanelSource, /Before-Match Inputs/);
  assert.doesNotMatch(reportsPanelSource, /Model Calibration, Model Features, Pre-Match Features/);
  assert.match(importsPanelSource, /function AdminV4ImportsPanel/);
  assert.match(importsPanelSource, /Official Source Import/);
  assert.match(importsPanelSource, /Upload Source Files/);
  assert.match(importsPanelSource, /official schedule/);
  assert.doesNotMatch(importsPanelSource, /TBA Data Import/);
  assert.doesNotMatch(importsPanelSource, /OPR\/COPR files/);
  assert.match(preScoutPanelSource, /function AdminV4PreScoutPanel/);
  assert.match(preScoutPanelSource, /Returned Pre Scout evidence is included/);
  assert.match(strategyPanelSource, /Model Trust/);
  assert.match(teamEvidenceSource, /function TeamEvidenceCoveragePanel/);
  assert.match(adminSource, /takeUniqueLaneRows/);
  assert.match(adminSource, /getPickLaneReason/);
  assert.match(adminSource, /renderPickStatusActions/);
  assert.match(adminSource, />\s*Status\s*<\/summary>/);
  assert.doesNotMatch(adminSource, />\s*Actions\s*<\/summary>/);
  assert.doesNotMatch(adminSource, /bg-cyan-600 px-2 py-1[^\\n]*Scout Check/);
  assert.doesNotMatch(pickListSource, /bg-cyan-600 px-2 py-1[^\\n]*Scout Check/);
  assert.match(adminSource, /primaryWorkflowItemIds/);
  assert.match(visualizeSource, /Choose The Question/);
  assert.match(visualizeSource, /Fine Tune Stats/);
  assert.match(visualizeSource, /Expected Range/);
  assert.match(visualizeSource, /Local Avg/);
  assert.match(visualizeSource, /Official Avg/);
  assert.doesNotMatch(visualizeSource, /label: 'PPC'/);
  assert.doesNotMatch(visualizeSource, /label: 'OPR'/);
  assert.doesNotMatch(visualizeSource, /label: 'DPR'/);
  assert.match(adminSource, /LazyAdminV4VisualizeWorkflow = React\.lazy/);
  assert.match(adminSource, /LazyAdminV4TeamsWorkflow = React\.lazy/);
  assert.match(adminSource, /LazyAdminV4MatchesWorkflow = React\.lazy/);
  assert.match(adminSource, /LazyAdminV4PickListWorkflow = React\.lazy/);
  assert.match(adminSource, /LazyAdminV4DataOverviewWorkflow = React\.lazy/);
  assert.match(adminSource, /LazyAdminV4ReportsPanel = React\.lazy/);
  assert.match(adminSource, /LazyAdminV4ScoutStaffingPanel = React\.lazy/);
  assert.match(adminSource, /<React\.Suspense fallback=\{<EmbeddedPanelLoading label=\{`Loading \$\{activeWorkspace\.label\}\.\.\.`\}/);
  assert.match(adminSource, /import type \{[\s\S]*AdminV4VisualChartConfig/);
  assert.doesNotMatch(adminSource, /import AdminV4VisualizeWorkflow,/);
  assert.doesNotMatch(adminSource, /import AdminV4TeamsWorkflow,/);
  assert.doesNotMatch(adminSource, /import AdminV4MatchesWorkflow,/);
  assert.doesNotMatch(adminSource, /import AdminV4PickListWorkflow/);
  assert.doesNotMatch(adminSource, /import AdminV4DataOverviewWorkflow,/);
  assert.doesNotMatch(adminSource, /import AdminV4ReportsPanel/);
  assert.doesNotMatch(adminSource, /from '..\/components\/adminv4\/AdminV4Charts'/);
  assert.match(reportsSource, /Show Full XLSX Export/);
  assert.match(reportsSource, /Audience Report Packs/);
  assert.match(reportsPanelSource, /Prediction Ledger Closeout/);
  assert.match(reportsPanelSource, /Forecast Snapshot checkpoint/);
  assert.match(reportsPanelSource, /Open Model Trust/);
  assert.match(reportsPanelSource, /Export Workbook/);
  assert.match(reportsSource, /All Report Pack Details/);
  assert.match(reportsSource, /admin-details-body/);
  assert.match(reportsSource, /audience shortcuts above are the normal competition path/);
  assert.match(cssSource, /details:not\(\[open\]\) > \.admin-details-body[\s\S]*display: none !important/);
  assert.match(commandBarSource, /placeholder="Search or ask: team, stat, scouts, export, API keys"/);
  assert.match(commandBarSource, /Search teams, stats, workflows, tools, settings, and data panels/);
  assert.match(commandBarSource, /SearchCheck/);
  assert.doesNotMatch(commandBarSource, /Users className/);
  assert.match(commandBarSource, /aria-keyshortcuts="\/"/);
  assert.match(commandBarSource, /Press \/ to focus search or Cmd\/Ctrl\+K for I need\.\.\./);
  assert.match(commandBarSource, /onClick=\{\(\) => onSetTeamSearchOpen\(true\)\}/);
  assert.match(commandBarSource, /onMouseDown=\{\(\) => onSetTeamSearchOpen\(true\)\}/);
  assert.match(commandBarSource, /searchInputRef/);
  assert.match(primitivesSource, /React\.forwardRef<HTMLInputElement/);
  assert.match(adminSource, /commandPaletteInputRef/);
  assert.match(adminSource, /commandPaletteInput/);
  assert.match(adminSource, /commandPaletteError/);
  assert.match(adminSource, /commandPaletteSuggestions/);
  assert.match(adminSource, /commandPaletteOpen/);
  assert.match(adminSource, /setCommandPaletteInput\(''\)/);
  assert.match(adminSource, /setCommandPaletteError\(''\)/);
  assert.match(adminSource, /setCommandPaletteOpen\(true\)/);
  assert.match(adminSource, /setIsTeamSearchOpen\(false\)/);
  assert.match(adminSource, /commandPaletteInputRef\.current\?\.focus\(\)/);
  assert.match(adminSource, /const openCommandPalette = useCallback/);
  assert.match(adminSource, /openCommandPalette\(\)/);
  assert.match(adminSource, /<AdminV4CommandPalette/);
  assert.match(commandPaletteSource, /role="dialog"/);
  assert.match(commandPaletteSource, /aria-modal="true"/);
  assert.match(commandPaletteSource, /I need\.\.\./);
  assert.match(commandPaletteSource, /Command Palette/);
  assert.match(commandPaletteSource, /openBestButtonLabel/);
  assert.match(commandPaletteSource, /openBestButtonText/);
  assert.doesNotMatch(commandPaletteSource, /Open Best Result/);
  assert.match(commandPaletteSource, /aria-label=\{openBestButtonLabel\}/);
  assert.match(commandPaletteSource, /title=\{openBestButtonLabel\}/);
  assert.match(commandPaletteSource, /event\.key === 'Enter'/);
  assert.match(commandPaletteSource, /event\.key === 'ArrowDown'/);
  assert.match(commandPaletteSource, /event\.key === 'ArrowUp'/);
  assert.match(commandPaletteSource, /event\.key === 'Escape'/);
  assert.match(commandPaletteSource, /adminv4-command-palette-results/);
  assert.match(commandPaletteSource, /focusAdjacentPaletteResult/);
  assert.match(commandPaletteSource, /aria-label=\{`Open \$\{suggestion\.title\}\. \$\{suggestion\.badge\}\. \$\{suggestion\.matchLabel\}\. \$\{suggestion\.description\}`\}/);
  assert.match(commandPaletteSource, /querySelector<HTMLButtonElement>\('button'\)/);
  assert.match(commandPaletteSource, /openBest\(\)/);
  assert.match(commandPaletteSource, /openNumberedSuggestion/);
  assert.match(commandPaletteSource, /!\(event\.altKey \|\| event\.ctrlKey\)/);
  assert.match(commandPaletteSource, /Alt\/Option\+1-8/);
  assert.doesNotMatch(commandPaletteSource, /hasSearchInput \|\| !\(event\.altKey \|\| event\.ctrlKey\)/);
  assert.match(commandPaletteSource, /hasSearchInput && index === 0 \? 'Enter' : `Alt \$\{index \+ 1\}`/);
  assert.match(commandPaletteSource, /Try scouts, simulator, pick list, DPR, Excel, sync, or a team name/);
  assert.match(commandPaletteSource, /Choose a quick need below/);
  assert.match(commandPaletteSource, /Open competition shortcut: \$\{suggestion\.title\}/);
  assert.match(commandPaletteSource, /min-h-24/);
  assert.match(commandPaletteSource, /Alt \{index \+ 1\}/);
  assert.match(commandPaletteSource, /!hasSearchInput/);
  assert.match(commandPaletteSource, /assign scouts/);
  assert.match(commandPaletteSource, /why DPR/);
  assert.match(commandPaletteSource, /future matches/);
  assert.match(commandPaletteSource, /API keys/);
  assert.match(commandPaletteSource, /demo proof/);
  assert.match(commandPaletteSource, /NO_MATCH_FALLBACK_PHRASES/);
  assert.match(commandPaletteSource, /Pick a recovery phrase, try a team name, or clear the field for Quick Needs/);
  assert.match(commandPaletteSource, /aria-label=\{`Search for \$\{phrase\}`\}/);
  assert.match(commandPaletteSource, /manual simulator/);
  assert.match(commandPaletteSource, /source freshness/);
  assert.match(commandPaletteSource, /COMMAND_PALETTE_EXAMPLE_PHRASES/);
  assert.match(commandPaletteSource, /bad numbers/);
  assert.match(commandPaletteSource, /future matches/);
  assert.match(commandPaletteSource, /const useSearchPhrase = \(phrase: string\)/);
  assert.match(commandPaletteSource, /onSetSearchInput\(phrase\)/);
  assert.match(commandPaletteSource, /commandInputRef\.current\?\.focus\(\)/);
  assert.match(commandPaletteSource, /React\.useEffect\(\(\) => \{/);
  assert.match(commandPaletteSource, /\}, \[open\]\);/);
  assert.match(adminSource, /searchInput=\{commandPaletteInput\}/);
  assert.match(adminSource, /suggestions=\{commandPaletteSuggestions\}/);
  assert.match(adminSource, /onSetSearchInput=\{setCommandPaletteInput\}/);
  assert.match(adminSource, /handleSmartSearchShortcut/);
  assert.match(adminSource, /isEditableShortcutTarget/);
  assert.match(adminSource, /event\.key === '\/'/);
  assert.match(adminSource, /smartSearchInputRef\.current\?\.focus\(\)/);
  assert.match(adminSource, /smartSearchInputRef\.current\?\.select\(\)/);
  assert.match(commandBarSource, /bestSearchSuggestion/);
  assert.match(commandBarSource, /openSearchButtonLabel/);
  assert.match(commandBarSource, /Show quick needs for teams, workflows, stats, tools, settings, and data panels/);
  assert.match(commandBarSource, /const openSearchButtonText = hasSearchInput \? 'Open' : 'Needs'/);
  assert.match(commandBarSource, /if \(!teamSearchInput\.trim\(\)\)/);
  assert.match(commandBarSource, /onOpenCommandPalette\(\)/);
  assert.match(commandBarSource, /aria-label=\{openSearchButtonLabel\}/);
  assert.match(commandBarSource, /title=\{openSearchButtonLabel\}/);
  assert.match(commandBarSource, /aria-label="Search teams, stats, workflows, tools, settings, and data panels"/);
  assert.match(commandBarSource, /Open the best matching team, workflow, stat, tool, or data panel/);
  assert.match(commandBarSource, /event\.key === 'ArrowDown'/);
  assert.match(commandBarSource, /event\.key === 'ArrowUp'/);
  assert.match(commandBarSource, /event\.key === 'Escape'/);
  assert.match(commandBarSource, /onSetTeamSearchOpen\(false\)/);
  assert.match(commandBarSource, /adminv4-team-search-suggestions/);
  assert.match(commandBarSource, /focusAdjacentSearchResult/);
  assert.match(commandBarSource, /aria-label=\{`Open \$\{suggestion\.title\}\. \$\{suggestion\.badge\}\. \$\{suggestion\.matchLabel\}\. \$\{suggestion\.description\}`\}/);
  assert.match(commandBarSource, /onOpenCommandPalette/);
  assert.match(commandBarSource, /<Command className="h-4 w-4" \/>/);
  assert.match(commandBarSource, /className="!inline-flex !min-h-10 !px-3 !py-2 text-xs lg:!hidden" tone="cyan" onClick=\{onOpenCommandPalette\} aria-label="I need\.\.\."/);
  assert.match(commandBarSource, /title="Open command palette"/);
  assert.match(commandBarSource, />I need<\/span>/);
  assert.match(primitivesSource, /mobileNeed\?: string/);
  assert.match(commandBarSource, /Open What You Need/);
  assert.match(commandBarSource, /Pick the situation, then the app opens the right workspace/);
  assert.match(commandBarSource, /item\.mobileNeed/);
  assert.match(adminSource, /mobileNeed: 'Use when you just need the next safe click\.'/);
  assert.match(adminSource, /mobileNeed: 'Use when a qual is coming up or drive team needs a plan\.'/);
  assert.match(adminSource, /mobileNeed: 'Use when numbers, sources, scouts, sync, or trust feel wrong\.'/);
  assert.match(adminSource, /mobileNeed: 'Use when mentors, visitors, or another laptop need proof\.'/);
  assert.match(adminSource, /onOpenCommandPalette=\{openCommandPalette\}/);
  assert.match(adminSource, /const \[teamSearchInput, setTeamSearchInput\] = useState\(''\)/);
  assert.match(adminSource, /setTeamSearchInput\(''\)/);
  assert.doesNotMatch(adminSource, /setTeamSearchInput\(searchedTeamNumber\)/);
  assert.doesNotMatch(adminSource, /setTeamSearchInput\(fixture\.searchedTeamNumber\)/);
  assert.doesNotMatch(adminSource, /setTeamSearchInput\(sanitizedTeamNumber\)/);
  assert.match(commandBarSource, /className="!hidden md:!inline-flex" onClick=\{onOpenStatsWiki\} aria-label="Open Stats Wiki"/);
  assert.match(commandBarSource, /BookOpen/);
  assert.match(commandBarSource, /Best Match First · Enter opens it/);
  assert.match(commandBarSource, /Quick Needs · fastest next click/);
  assert.match(commandBarSource, /No matches for/);
  assert.match(commandBarSource, /Open the larger I need\.\.\. palette for recovery phrases/);
  assert.match(commandBarSource, /Open I need\.\.\./);
  assert.doesNotMatch(commandBarSource, /TOP_SEARCH_FALLBACK_PHRASES/);
  assert.doesNotMatch(commandBarSource, /TOP_SEARCH_EXAMPLE_PHRASES/);
  assert.doesNotMatch(commandBarSource, /Pick a recovery phrase, try a team name, or clear the field for Quick Needs/);
  assert.doesNotMatch(commandBarSource, /const useSearchPhrase = \(phrase: string\)/);
  assert.doesNotMatch(nowSource, /Data Health/);
  assert.doesNotMatch(matchesSource, /Data Health/);
  assert.doesNotMatch(teamsSource, /Data Health/);
  assert.match(teamsSource, /AdminV4TeamsDecisionCue/);
  assert.match(teamsSource, /Do This First/);
  assert.match(teamsSource, /decisionCue\.actionLabel/);
  assert.ok(
    teamsSource.indexOf('Do This First') < teamsSource.indexOf('<div className="mt-4">{teamControls}</div>'),
    'Teams should show the decision cue before metric/model controls'
  );
  assert.match(teamsSource, /Show Leaderboard Metric Translation/);
  assert.match(teamsSource, /admin-details-body/);
  assert.match(teamsSource, /Leaderboard Column Translation/);
  assert.match(teamsSource, /Use this before sorting/);
  assert.match(teamsSource, /right-click any metric label, info icon, or sortable column for Get Info/);
  assert.match(teamsSource, /function MobileMetricLabel/);
  assert.match(teamsSource, /shouldIgnoreTeamCardOpen/);
  assert.match(teamsSource, /data-adminv4-stop-team-open="true"/);
  assert.match(teamsSource, /onPointerDown=\{event => event\.stopPropagation\(\)\}/);
  assert.match(teamsSource, /aria-label=\{`Get info for \$\{label\}`\}/);
  assert.match(teamsSource, /MobileMetricLabel label="Expected" infoKey="ppa"/);
  assert.match(teamsSource, /MobileMetricLabel label="Floor" infoKey="ppaFloor"/);
  assert.match(teamsSource, /MobileMetricLabel label="Ceiling" infoKey="ppaCeiling"/);
  assert.match(teamsSource, /MobileMetricLabel label="Defense" infoKey="defenseMetric"/);
  assert.match(teamsSource, /MobileMetricLabel label="Official avg" infoKey="opr"/);
  assert.match(teamsSource, /MobileMetricLabel label="Public rating" infoKey="epa"/);
  assert.match(matchesSource, /AdminV4MatchesNextAction/);
  assert.match(matchesSource, /Do This First/);
  assert.match(matchesSource, /nextAction\.actionLabel/);
  assert.match(matchesSource, /const matchControls = \(/);
  assert.ok(
    matchesSource.indexOf('Do This First') < matchesSource.indexOf('<div className="mt-4 hidden md:block">{matchControls}</div>'),
    'Matches should show next-match action before model/manual controls'
  );
  assert.match(matchesSource, /mt-5 hidden w-full flex-col gap-3 border p-4/);
  assert.match(matchesSource, /Phone Match Prep/);
  assert.match(matchesSource, /Use the next known match first; use manual sim only for custom alliances/);
  assert.match(matchesSource, /aria-label=\{`Open match prep shortcut: \$\{nextAction\.label\}\. \$\{nextAction\.detail\}`\}/);
  assert.match(matchesSource, /Open manual simulator for a custom what-if alliance/);
  assert.match(matchesSource, /Open expected range math for match forecasts/);
  assert.match(pickListSource, /AdminV4PickListDecisionCue/);
  assert.match(pickListSource, /Do This First/);
  assert.match(pickListSource, /decisionCue\.actionLabel/);
  assert.match(pickListSource, /const pickListControls = \(/);
  assert.ok(
    pickListSource.indexOf('Do This First') < pickListSource.indexOf('<div className="mt-4">{pickListControls}</div>'),
    'Pick List should show alliance decision cue before meeting controls'
  );
  assert.match(pickListSource, /Show Pick-List Metric Translation/);
  assert.match(pickListSource, /admin-details-body/);
  assert.match(visualizeSource, /visualizeFirstAction/);
  assert.match(visualizeSource, /Do This First/);
  assert.match(visualizeSource, /Explain Stat/);
  assert.match(visualizeSource, /const visualizeControls = \(/);
  assert.ok(
    visualizeSource.indexOf('Do This First') < visualizeSource.indexOf('<div className="mt-4">{visualizeControls}</div>'),
    'Visualize should show the chart question action before stat-picker controls'
  );
  assert.match(visualizeSource, /Show Metric Translation/);
  assert.match(visualizeSource, /admin-details-body/);
  assert.match(statControlsSource, /PlainStatTeachingStrip/);
  assert.match(statControlsSource, /Click any metric to open the Stats Wiki/);
  assert.match(statControlsSource, /Right-click any metric for Get Info/);
  assert.match(statControlsSource, /aria-label=\{`Open Stats Wiki for \$\{item\.label\}: \$\{item\.plain\}`\}/);
  assert.match(statControlsSource, /Best current guess, not a promise/);
  assert.match(statControlsSource, /Cautious value to trust in tight calls/);
  assert.match(statControlsSource, /How likely the range is to disappoint/);
  assert.match(teamsSource, /PlainStatTeachingStrip/);
  assert.match(pickListSource, /Pick-List Metric Translation/);
  assert.match(visualizeSource, /Chart Metric Translation/);
  assert.match(visualizeSource, /Start with a question, then click any metric to open the exact Stats Wiki entry/);
  assert.match(visualizeSource, /Right-click metric chips or chart panels for Get Info/);
  assert.match(reportsSource, /recommendedPackKey/);
  assert.match(reportsSource, /Do This First/);
  assert.match(reportsSource, /recommendedAction\.label/);
  assert.ok(
    reportsSource.indexOf('Do This First') < reportsSource.indexOf('<div className="mt-4">{modelAction}</div>'),
    'Reports should show the recommended audience action before report model controls'
  );
  assert.match(dataOverviewSource, /Say the problem, not the panel name/);
  assert.match(dataOverviewSource, /schedule stale, scouts missing, numbers wrong, model trust, returned evidence, or device handoff/);
  assert.match(dataOverviewSource, /aria-label=\{`Open Data help to \$\{need\.label\}\. \$\{need\.detail\}`\}/);
  assert.match(reportsSource, /If Someone Asks\.\.\./);
  assert.match(reportsSource, /Pick the audience first/);
  assert.match(reportsSource, /head scout, drive team, pick-list lead, model proof, or data owner/);
  assert.match(reportsSource, /aria-label=\{`Open report for \$\{pack\.audience\}: \$\{pack\.title\}\. \$\{pack\.when\}`\}/);
  assert.match(adminSource, /teamsDecisionCue/);
  assert.match(adminSource, /Fix low-trust teams before ranking too hard/);
  assert.match(adminSource, /matchesNextAction/);
  assert.match(adminSource, /Open our next plan/);
  assert.match(adminSource, /pickListDecisionCue/);
  assert.match(adminSource, /Review \$\{topAvailableRows\[0\]\.teamNumber\} before changing the board/);
  assert.match(reportsPanelSource, /recommendedPackKey/);
  assert.match(reportsPanelSource, /\? 'evidence'/);
  assert.doesNotMatch(dataOverviewSource, /Data Rooms And Maintenance/);
  assert.match(adminSource, /title: 'Check Model Trust'/);
  assert.match(adminSource, /model-trust checks/);
  assert.match(commandBarSource, /AdminV4CommandBrief/);
  assert.match(commandBarSource, /commandBrief/);
  assert.match(commandBarSource, />\s*Next\s*<\/span>/);
  assert.match(commandBarSource, /inline-flex min-h-10/);
  assert.match(adminSource, /getAdminV4SmartSearchSuggestions/);
  assert.match(adminSource, /openSmartSearchResult/);
  assert.match(adminSource, /suggestion\.tool === 'statsWiki'/);
  assert.match(adminSource, /onOpenStatsWiki=\{\(\) => openWiki\('ppa', activeTab\)\}/);
  assert.match(adminSource, /globalCommandBrief/);
  assert.match(adminSource, /Collect evidence before/);
  assert.match(smartSearchSource, /quickTitle: 'Assign scouts'/);
  assert.match(smartSearchSource, /quickTitle: 'Open demo proof'/);
  assert.match(smartSearchSource, /quickDescription: 'Open vertical chart panels/);
  assert.match(adminSource, /primaryEvidenceGapTeams\.length > 0\s*\?\s*\[evidenceNowAction, prepareNowAction, rangeNowAction, sourceNowAction\]/);
  assert.match(teamSearchSource, /getAdminV4TeamSearchSuggestions/);
  assert.match(teamSearchSource, /Exact name/);
  assert.match(teamSearchSource, /Name contains/);
  assert.match(smartSearchSource, /scout assignments/);
  assert.match(smartSearchSource, /manualSimulator/);
  assert.match(smartSearchSource, /Stat Help/);
  assert.match(smartSearchSource, /describeStatSearchResult/);
  assert.match(smartSearchSource, /Appears in \$\{whereAppears\.slice\(0, 4\)\.join\(', '\)\}/);
  assert.match(smartSearchSource, /tool-stats-wiki/);
  assert.match(smartSearchSource, /what does this stat mean/);
  assert.match(smartSearchSource, /SMART_SEARCH_INTENT_WORDS/);
  assert.match(smartSearchSource, /Quick need/);
  assert.match(smartSearchSource, /title: 'Data'/);
  assert.match(smartSearchSource, /title: 'Scout Evidence Queue'/);
  assert.match(smartSearchSource, /match soon/);
  assert.match(smartSearchSource, /data looks wrong/);
  assert.match(smartSearchSource, /judges are here/);
  assert.match(smartSearchSource, /drive team needs a plan/);
  assert.match(smartSearchSource, /defend alliance choices/);
  assert.match(commandBarSource, /MoreHorizontal/);
  assert.match(commandBarSource, /aria-label="Admin workflows"/);
  assert.match(commandBarSource, /aria-label=\{`\$\{item\.label\}: \$\{item\.description\}\. \$\{item\.mobileNeed \|\| ''\}`\.trim\(\)\}/);
  assert.match(commandBarSource, /title=\{`\$\{item\.label\}: \$\{item\.description\}\. \$\{item\.mobileNeed \|\| ''\}`\.trim\(\)\}/);
  assert.match(commandBarSource, /commandBriefAccessibleLabel/);
  assert.match(commandBarSource, /commandBrief\.detail\.replace\(\//);
  assert.match(commandBarSource, /aria-label=\{commandBriefAccessibleLabel\}/);
  assert.match(commandBarSource, /title=\{commandBriefAccessibleLabel\}/);
  assert.match(commandBarSource, /className="!hidden md:!inline-flex"/);
  assert.doesNotMatch(commandBarSource, /<select/);
  assert.match(workflowSource, /getAdminUseMomentRoute = \(key: ScoutingUseMomentKey, currentSearch/);
  assert.match(workflowSource, /buildAdminV4Route\(currentSearch/);
  assert.match(adminSource, /queueBackgroundRefreshForWorkflow/);
  assert.match(adminSource, /pendingBackgroundRefreshTabRef/);
  assert.match(adminSource, /minimumRefreshSignalMs = 800/);
  assert.match(adminSource, /loadV3Data\(\{ background: true, preserveScroll: true \}\)/);
  assert.match(adminSource, /setBackgroundRefreshing\(true\)/);
  assert.match(adminSource, /setBackgroundRefreshing\(false\)/);
  assert.match(adminSource, /listAdminV4CacheEntries\(eventKey\)/);
  assert.match(adminSource, /getLatestAdminV4CachePayload/);
  assert.match(adminSource, /setSourceLiveEventMatches\(cachedMatches\)/);
  assert.match(adminSource, /createScrollSnapshot\(options\.preserveScroll\)/);
  assert.match(scrollHookSource, /viewScrollPositionsRef\.current\[scrollKey\]/);
  assert.match(scrollHookSource, /React\.useLayoutEffect/);
  assert.match(adminSource, /<main ref=\{mainScrollRef\}/);
  assert.match(commandBarSource, /backgroundRefreshing/);
  assert.match(commandBarSource, /animate-spin/);
  assert.match(adminSource, /Defense Metric Guardrail/);
  assert.match(adminSource, /Review Defense Metrics/);
  assert.match(strategyCopySource, /ownPerspective/);
  assert.match(strategyCopySource, /Our \$\{selectedAlliance\.toLowerCase\(\)\} alliance/);
  assert.match(strategyCopySource, /\$\{selectedAlliance\} alliance/);
  assert.match(commandBarSource, /md:hidden/);
  assert.match(commandBarSource, /md:flex/);
  assert.match(commandBarSource, /!hidden md:!inline-flex/);
  assert.doesNotMatch(adminSource, /Strategy Brain/);
  assert.doesNotMatch(adminSource, /Scout Ops/);
  assert.doesNotMatch(adminSource, /Sidebar/);
  assert.doesNotMatch(adminSource, /Model Lab/);
  assert.doesNotMatch(adminSource, /No-Future Feature Matrix/);
  assert.doesNotMatch(adminSource, /rounded-(xl|2xl|3xl|full)/);
  assert.doesNotMatch(ppaSource, /High confidence|Medium confidence|Low confidence|High model trust|Medium model trust|Low model trust/);
  assert.match(ppaSource, /Trust for plan/);
  assert.match(guardSource, /Check Access Again/);
  assert.match(guardSource, /Copy Access Request/);
  assert.match(guardSource, /Event:/);
  assert.match(guardSource, /Own team:/);
  assert.match(guardSource, /adminRoles\/\$\{accessState\?\.uid/);
  assert.doesNotMatch(guardSource, /REFRESH ADMIN ACCESS/);
});

test('Admin V4 visualize and stat help use the intended interaction model', () => {
  const adminSource = readFileSync('src/views/AdminV4View.tsx', 'utf8');
  const statDefinitionSource = readFileSync('src/components/adminv4/AdminV4StatDefinitions.ts', 'utf8');
  const statControlSource = readFileSync('src/components/adminv4/AdminV4StatControls.tsx', 'utf8');
  const chartSource = readFileSync('src/components/adminv4/AdminV4Charts.tsx', 'utf8');
  const visualizeSource = readFileSync('src/components/adminv4/AdminV4VisualizeWorkflow.tsx', 'utf8');
  const statWikiSource = readFileSync('src/components/adminv4/AdminV4StatWiki.tsx', 'utf8');
  const ppaPanelSource = readFileSync('src/components/adminv4/AdminV4PpaPanels.tsx', 'utf8');
  const ppaSource = readFileSync('src/utils/ppaInsights.ts', 'utf8');
  const pickListSource = readFileSync('src/components/adminv4/AdminV4PickListWorkflow.tsx', 'utf8');
  const teamEvidenceSource = readFileSync('src/components/adminv4/AdminV4TeamEvidencePanels.tsx', 'utf8');
  const statHelpInteractionSource = [
    adminSource,
    statControlSource,
    chartSource,
    ppaPanelSource,
    pickListSource,
    teamEvidenceSource
  ].join('\n');

  assert.match(adminSource, /Stats Wiki/);
  assert.match(adminSource, /Get Info/);
  assert.match(adminSource, /const \{ statKey \} = infoMenu/);
  assert.match(adminSource, /setInfoMenu\(null\);\s+openWiki\(statKey\);/);
  assert.match(statWikiSource, /activeEntryRef/);
  assert.match(statWikiSource, /wikiSearch/);
  assert.match(statWikiSource, /visibleEntries/);
  assert.match(statWikiSource, /Search Stats Wiki entries/);
  assert.match(statWikiSource, /Find Stat/);
  assert.match(statWikiSource, /No stat matches/);
  assert.match(statWikiSource, /In A Hurry/);
  assert.match(statWikiSource, /Use This When/);
  assert.match(statWikiSource, /Check First/);
  assert.match(statWikiSource, /Find It In/);
  assert.match(statWikiSource, /scrollIntoView\(\{ block: 'center' \}\)/);
  assert.match(statWikiSource, /aria-current=\{key === activeKey \? 'true' : undefined\}/);
  assert.match(statHelpInteractionSource, /onContextMenu/);
  assert.match(adminSource, /role="menuitem"/);
  assert.match(statDefinitionSource, /ADMIN_V4_STAT_INFO/);
  assert.match(statDefinitionSource, /ppaExpected/);
  assert.match(statDefinitionSource, /defenseImpact/);
  assert.doesNotMatch(statDefinitionSource, /public fallback|public\/model fallback|or unknown/);
  assert.match(statDefinitionSource, /public rating context/);
  assert.match(statDefinitionSource, /needs role evidence/);
  [
    'ppc',
    'autoPpc',
    'teleopPpc',
    'ppa',
    'opr',
    'epa',
    'dpr',
    'defenseMetric',
    'defenseImpact',
    'tbaRank',
    'matches',
    'volatility',
    'projectedRank',
    'rpForecast'
  ].forEach(statKey => {
    const entryMatch = statDefinitionSource.match(new RegExp(`${statKey}: \\{[\\s\\S]*?\\n  \\}`));
    assert.ok(entryMatch, `${statKey} wiki entry exists`);
    assert.match(entryMatch[0], /whereAppears:/, `${statKey} declares where it appears`);
  });
  assert.match(statControlSource, /function ModelToggleGroup/);
  assert.match(statControlSource, /ppa: 'Expected'/);
  assert.match(statControlSource, /ppc: 'Local Avg'/);
  assert.match(statControlSource, /opr: 'Official Avg'/);
  assert.match(statControlSource, /epa: 'Public Rating'/);
  assert.match(statControlSource, /Explain selected model/);
  assert.match(statControlSource, /ADMIN_V4_MODEL_HELP/);
  assert.match(statControlSource, /Selected model explanation/);
  assert.match(statControlSource, /Admin V4 expected range from local scouting/);
  assert.match(statControlSource, /Use: \{selectedHelp\.use\} Watch: \{selectedHelp\.watch\}/);
  assert.match(statControlSource, /onContextMenu=\{event => onInfoContext\?\.\(event, selectedMetric\)\}/);
  assert.doesNotMatch(statControlSource, /Explain \$\{labelText\} model/);
  assert.match(statControlSource, /function StatInfoButton/);
  assert.match(statControlSource, /inline-flex h-10 w-10/);
  assert.match(statControlSource, /function StatChip/);
  assert.match(statControlSource, /min-h-10 px-3 py-2/);
  assert.match(adminSource, /role="menuitem"[\s\S]*className="flex min-h-10/);
  assert.match(chartSource, /function VerticalStatBarChart/);
  assert.match(chartSource, /function PpaShapeBarChart/);
  assert.match(chartSource, /MAX_BARS_PER_CHART_PANEL = 12/);
  assert.match(chartSource, /chunkAdminV4ChartRows/);
  assert.match(chartSource, /2xl:grid-cols-2/);
  assert.match(chartSource, /Teams \$\{index \* MAX_BARS_PER_CHART_PANEL \+ 1\}-/);
  assert.match(chartSource, /Expected Range Shape/);
  assert.match(visualizeSource, /AdminV4VisualizeWorkflow/);
  assert.match(ppaPanelSource, /function PpaInsightPanel/);
  assert.match(ppaPanelSource, /Expected Range Matchup/);
  assert.match(ppaPanelSource, /Scout Trust/);
  assert.match(ppaPanelSource, /Advanced model proof/);
  assert.match(ppaPanelSource, /admin-details-body mt-2 text-slate-500/);
  assert.match(ppaSource, /Treat Team \$\{teamNumber\} as/);
  assert.doesNotMatch(ppaSource, /sourceModelName\} says Team/);
  assert.match(pickListSource, /Pick Score/);
  assert.match(teamEvidenceSource, /Expected Range Shape/);
  assert.doesNotMatch(
    [chartSource, ppaPanelSource, pickListSource, teamEvidenceSource, visualizeSource, adminSource].join('\n'),
    /PPA Decision Shape|PPA Matchup Read|PPA Pick Score|No high-risk PPA|PPA evidence chain|PPA Question Closed|No PPA shape yet|Manual PPA/
  );
  assert.match(chartSource, /RechartsBarChart/);
  assert.match(chartSource, /XAxis/);
  assert.match(chartSource, /YAxis/);
  assert.match(chartSource, /right-click this chart for the Stats Wiki entry behind the math/);
  assert.match(chartSource, /right-click this chart for the formula, source, interpretation, and limitations/);
  assert.doesNotMatch(adminSource, /function VerticalStatBarChart/);
  assert.doesNotMatch(adminSource, /function PpaInsightPanel/);
  assert.doesNotMatch(adminSource, /function PpaMiniShape/);
  assert.doesNotMatch(adminSource, /function TeamEvidenceCoveragePanel/);
  assert.doesNotMatch(adminSource, /function SimulatorTeamTable/);
  assert.doesNotMatch(adminSource, /function PlayoffMatchCard/);
  assert.doesNotMatch(adminSource, /function SimulatorAllianceCard/);
});

test('Admin V4 primitives are active and not sidebar-era placeholders', () => {
  const primitivesSource = readFileSync('src/components/adminv4/AdminV4Primitives.tsx', 'utf8');
  const commandBarSource = readFileSync('src/components/adminv4/AdminV4CommandBar.tsx', 'utf8');
  const adminSource = readFileSync('src/views/AdminV4View.tsx', 'utf8');
  const guardSource = readFileSync('src/components/admin/AdminGuard.tsx', 'utf8');
  const atomSource = readFileSync('src/components/adminv4/AdminV4UiAtoms.tsx', 'utf8');

  assert.match(primitivesSource, /role="dialog"/);
  assert.match(primitivesSource, /aria-modal="true"/);
  assert.match(primitivesSource, /React\.useId\(\)/);
  assert.match(primitivesSource, /aria-labelledby=\{titleId\}/);
  assert.doesNotMatch(primitivesSource, /admin-modal-title/);
  assert.match(primitivesSource, /shadow-sm shadow-slate-950\/10/);
  assert.match(primitivesSource, /inline-flex h-10 w-10/);
  assert.match(primitivesSource, /<X aria-hidden="true"/);
  assert.match(primitivesSource, /ArrowDown/);
  assert.match(primitivesSource, /ArrowUp/);
  assert.match(primitivesSource, /window\.innerWidth - 220/);
  assert.match(primitivesSource, /window\.innerHeight - 180/);
  assert.match(primitivesSource, /function DangerZone/);
  assert.doesNotMatch(primitivesSource, /function AdminConfirmButton/);
  assert.doesNotMatch(primitivesSource, /window.confirm/);
  assert.match(atomSource, /function FocusHeader/);
  assert.match(atomSource, /lg:min-w-64 lg:flex-1/);
  assert.match(atomSource, /lg:max-w-\[60%\]/);
  assert.doesNotMatch(atomSource, /\{action && <div className="shrink-0"/);
  assert.match(atomSource, /function AdminEmptyState/);
  assert.match(atomSource, /Why:/);
  assert.match(atomSource, /Next:/);
  assert.match(adminSource, /<AdminEmptyState/);
  assert.match(atomSource, /function TeamBadge/);
  assert.match(atomSource, /getTeamBadgeClass/);
  assert.doesNotMatch(primitivesSource, /WorkspaceNav/);
  assert.doesNotMatch(primitivesSource, /function ActionGroup/);
  assert.doesNotMatch(primitivesSource, /function MetricBarChart/);
  assert.doesNotMatch(
    [primitivesSource, commandBarSource, adminSource, guardSource].join('\n'),
    /shadow-xl|shadow-2xl|bg-gradient/
  );
});

test('Admin V4 stages sensitive local operations with confirmations and a local audit log', () => {
  const adminSource = readFileSync('src/views/AdminV4View.tsx', 'utf8');
  const localStoreSource = readFileSync('src/utils/adminV4LocalStore.ts', 'utf8');
  const backupImportSource = readFileSync('src/utils/adminV4BackupImport.ts', 'utf8');
  const backupPreviewSource = readFileSync('src/components/adminv4/AdminV4BackupRestorePreviewModal.tsx', 'utf8');
  const safetyModalSource = readFileSync('src/components/adminv4/AdminV4SafetyModals.tsx', 'utf8');
  const staffingSource = readFileSync('src/components/adminv4/AdminV4ScoutStaffingPanel.tsx', 'utf8');
  const rewardsPanelSource = readFileSync('src/components/adminv4/AdminV4ScoutRewardsPanel.tsx', 'utf8');
  const ppaPanelsSource = readFileSync('src/components/adminv4/AdminV4PpaPanels.tsx', 'utf8');
  const settingsModalSource = readFileSync('src/components/adminv4/AdminV4SettingsModal.tsx', 'utf8');
  const modelValidationSource = readFileSync('src/components/adminv4/AdminV4ModelValidationPanel.tsx', 'utf8');
  const scoutIdentityLockSource = readFileSync('src/utils/scoutIdentityLock.ts', 'utf8');
  const scoutIdentityHookSource = readFileSync('src/components/adminv4/useAdminV4ScoutIdentitySettings.ts', 'utf8');
  const backupSyncPanelSource = readFileSync('src/components/adminv4/AdminV4BackupSyncPanel.tsx', 'utf8');

  assert.match(adminSource, /recordAdminAudit/);
  assert.match(backupSyncPanelSource, /Admin Operation Log/);
  assert.match(adminSource, /requestAdminActionConfirmation/);
  assert.match(adminSource, /useAdminV4ActionConfirmation/);
  assert.doesNotMatch(adminSource, /setAdminActionConfirmation/);
  assert.match(adminSource, /AdminV4ActionConfirmationModal/);
  assert.match(safetyModalSource, /Confirm Admin Action/);
  assert.match(settingsModalSource, /Local Credential Danger Zone/);
  assert.match(settingsModalSource, /Competition Setup Check/);
  assert.match(settingsModalSource, /Can this device run the event right now\?/);
  assert.match(settingsModalSource, /No secrets are shown here/);
  assert.match(settingsModalSource, /credentialState/);
  assert.match(settingsModalSource, /sourceState/);
  assert.match(settingsModalSource, /rehearsalState/);
  assert.match(settingsModalSource, /API keys and FIRST credentials remain local to this browser\/device/);
  assert.match(settingsModalSource, /Relay Outbox Drafts/);
  assert.match(settingsModalSource, /Copy-Only Head Scout Alerts/);
  assert.match(settingsModalSource, /Prediction Checkpoint/);
  assert.match(settingsModalSource, /save a Forecast Snapshot in Model Trust/);
  assert.match(settingsModalSource, /does not send them automatically/);
  assert.match(settingsModalSource, /does not store relay passwords, device tokens, or DirectChat account secrets/);
  assert.match(settingsModalSource, /Clear FIRST/);
  assert.match(settingsModalSource, /Clear TBA/);
  assert.match(settingsModalSource, /Scout Identity Lock/);
  assert.match(settingsModalSource, /Copy Passphrase/);
  assert.match(settingsModalSource, /Scout-facing hash/);
  assert.match(settingsModalSource, /admin-only backend reminder/);
  assert.match(scoutIdentityLockSource, /DEFAULT_SCOUT_IDENTITY_UNLOCK_HASH/);
  assert.doesNotMatch(scoutIdentityLockSource, /leoscout/);
  assert.match(scoutIdentityHookSource, /saveScoutIdentityAdminSecret/);
  assert.match(scoutIdentityHookSource, /loadScoutIdentityAdminSecret/);
  assert.doesNotMatch(scoutIdentityHookSource, /leoscout/);
  assert.match(adminSource, /Clear FIRST Credentials/);
  assert.match(adminSource, /Clear TBA API Key/);
  assert.match(adminSource, /Preview Firebase Sync/);
  assert.match(adminSource, /recordTypeCounts/);
  assert.match(adminSource, /will be checked for conflicts before upload/);
  assert.match(adminSource, /Export Full Evidence Workbook/);
  assert.match(adminSource, /saveForecastSnapshotNow/);
  assert.match(adminSource, /Saved manual forecast snapshot at/);
  assert.match(modelValidationSource, /Save Forecast Snapshot/);
  assert.match(modelValidationSource, /onSaveForecastSnapshot/);
  assert.doesNotMatch(adminSource, /window\.confirm/);
  assert.match(backupSyncPanelSource, /Preview And Sync To Firebase/);
  assert.match(backupSyncPanelSource, /Preview Import Backup/);
  assert.match(backupPreviewSource, /Preview Backup Restore/);
  assert.match(backupPreviewSource, /Restore Selected Sections/);
  assert.match(backupImportSource, /DEFAULT_BACKUP_IMPORT_OPTIONS/);
  assert.match(backupImportSource, /countBackupImportCategory/);
  assert.match(backupImportSource, /settings: false/);
  assert.match(adminSource, /Choose at least one backup section before restoring/);
  assert.match(adminSource, /AdminV4BackupRestorePreviewModal/);
  assert.match(adminSource, /powerCoinSettlementRequest/);
  assert.match(adminSource, /AdminV4PowerCoinSettlementModal/);
  assert.doesNotMatch(adminSource, /AdminV4ScoutRewardsPanel/);
  assert.match(staffingSource, /AdminV4ScoutRewardsPanel/);
  assert.match(rewardsPanelSource, /Open Reward Predictions/);
  assert.match(rewardsPanelSource, /Pending Points/);
  assert.match(rewardsPanelSource, /settled returns/);
  assert.match(rewardsPanelSource, /Reward operations are separate from scouting decisions/);
  assert.match(rewardsPanelSource, /Manual Reward Adjustment/);
  assert.match(rewardsPanelSource, /Before Apply/);
  assert.match(rewardsPanelSource, /After Apply/);
  assert.match(rewardsPanelSource, /Reason Required/);
  assert.match(rewardsPanelSource, /disabled=\{!adjustmentReady\}/);
  assert.match(rewardsPanelSource, /Top Reward Balances/);
  assert.match(safetyModalSource, /Confirm Scout Reward Settlement/);
  assert.match(safetyModalSource, /open reward prediction/);
  assert.match(safetyModalSource, /Pending Points/);
  assert.match(safetyModalSource, /pending point/);
  assert.match(safetyModalSource, /Confirm Settlement/);
  assert.match(rewardsPanelSource, /Preview settlement for/);
  assert.match(rewardsPanelSource, /min-h-10 border border-slate-700 bg-slate-800/);
  assert.doesNotMatch(rewardsPanelSource, /Prediction stakes|Open Stake|currently staked/);
  assert.doesNotMatch(safetyModalSource, /Open Stake|currently staked/);
  assert.doesNotMatch(ppaPanelsSource, /betting/i);
  assert.doesNotMatch(adminSource, /Total Staked|header: 'Stake'|header: "Stake"/);
  assert.match(adminSource, /Total Allocated/);
  assert.match(adminSource, /Allocated Points/);
  assert.match(backupSyncPanelSource, /Export Safe Summary/);
  assert.match(adminSource, /containsScoutNames: false/);
  assert.match(backupSyncPanelSource, /This backup may contain team strategy, scout names/);
  assert.match(adminSource, /Download the full Admin V4 evidence workbook/);
  assert.match(adminSource, /Use the audience report packs if you only need a safer handoff/);
  assert.match(localStoreSource, /AdminV4AuditLogEntry/);
  assert.match(localStoreSource, /adminAuditLog/);
});

test('Admin V4 keeps audit-required ownership and review documents in the repo', () => {
  const stateMapPath = 'docs/adminv4-state-ownership.md';
  const checklistPath = 'docs/adminv4-competition-review-checklist.md';
  const overnightReportPath = 'docs/scouting-overnight-report-2026-06-28.md';
  const completionStatusPath = 'audits/ADMINV4_UX_CRITIQUE_COMPLETION_STATUS_2026-05-30.md';
  const visualQaSource = readFileSync('scripts/adminv4-visual-qa.mjs', 'utf8');
  const readinessSource = readFileSync('scripts/scouting-competition-readiness.mjs', 'utf8');
  const headScoutStatusPath = 'scripts/scouting-head-scout-status.mjs';
  const headScoutStatusSource = readFileSync(headScoutStatusPath, 'utf8');
  const e2eSource = readFileSync('tests/e2e/app.spec.ts', 'utf8');
  const packageSource = readFileSync('package.json', 'utf8');
  assert.ok(existsSync(stateMapPath), 'state ownership map exists');
  assert.ok(existsSync(checklistPath), 'competition review checklist exists');
  assert.ok(existsSync(overnightReportPath), 'overnight report draft exists');
  assert.ok(existsSync(completionStatusPath), 'completion status audit exists');
  assert.ok(existsSync(headScoutStatusPath), 'head scout status script exists');

  const stateMap = readFileSync(stateMapPath, 'utf8');
  const checklist = readFileSync(checklistPath, 'utf8');
  const overnightReport = readFileSync(overnightReportPath, 'utf8');
  const completionStatus = readFileSync(completionStatusPath, 'utf8');

  [
    'Routing and View Context',
    'Event and Admin Settings',
    'Local Credentials and Device-Only Secrets',
    'Test Mode Fixture Data',
    'Derived Decision State',
    'Scout-Facing Task Context'
  ].forEach(section => assert.match(stateMap, new RegExp(section)));
  assert.match(stateMap, /stored only in this browser on this device/);
  assert.match(stateMap, /Fixture mode is an explicit route context/);
  assert.match(stateMap, /Handoff URLs must not carry sensitive strategy/);

  [
    'Browser and Mobile QA',
    'Match-Day Workflow QA',
    'Data and Safety QA',
    'Scout-Facing QA',
    'Comprehension QA',
    'Accessibility QA'
  ].forEach(section => assert.match(checklist, new RegExp(section)));
  assert.match(checklist, /first viewport shows the next decision/);
  assert.match(checklist, /Visualize must render vertical bar charts/);
  assert.match(checklist, /split into stacked\/wrapped chart panels/);
  assert.match(checklist, /PPA.*should appear in stat help/);
  assert.match(checklist, /npm run check:head-scout/);
  assert.match(packageSource, /"check:head-scout": "node scripts\/scouting-head-scout-status\.mjs"/);
  assert.match(headScoutStatusSource, /Head Scout Status/);
  assert.match(headScoutStatusSource, /Morning operating cues/);
  assert.match(headScoutStatusSource, /Admin V4:/);
  assert.match(headScoutStatusSource, /adminv2\/prediction-vs-actual/);
  assert.match(headScoutStatusSource, /Reports -> Prediction Ledger Closeout/);
  assert.match(headScoutStatusSource, /scouting-competition-readiness\.mjs/);
  assert.doesNotMatch(headScoutStatusSource, /open Admin V4"|open Admin V2"|POST|THEBUTTON_RECEIVER_TOKEN|THEBUTTON_JOIN_PASSWORD|DirectChat account secrets/);
  assert.match(readinessSource, /SCOUTING_READINESS_FETCH_RETRIES/);
  assert.match(readinessSource, /after retry/);
  assert.match(overnightReport, /After our overnight work/);
  assert.match(overnightReport, /competition operating system/);
  assert.match(overnightReport, /npm run check:head-scout/);
  assert.match(overnightReport, /Reports -> Prediction Ledger Closeout/);
  assert.match(overnightReport, /The Button primary relay: HTTP 404/);
  assert.match(overnightReport, /DirectChat backup relay: HTTP 200/);
  assert.match(completionStatus, /Current Local Evidence/);
  assert.match(completionStatus, /Final Completion Evidence/);
  assert.match(completionStatus, /Firebase Hosting and Firestore rules deploy completed/);
  assert.match(completionStatus, /Hosted current-build chunks returned `200`/);
  assert.match(completionStatus, /user-confirmed after the current deploy/);
  assert.match(completionStatus, /live signed-in Admin V4 page/);
  assert.doesNotMatch(completionStatus, /Hosted deployment verification is complete only for the earlier Firebase Hosting\/static asset build/);
  assert.doesNotMatch(completionStatus, /current local build.*not been redeployed/);
  assert.match(visualQaSource, /button\[aria-label="Admin workflows"\]/);
  assert.match(visualQaSource, /adminv4-final-collection\.png/);
  assert.match(visualQaSource, /What to send scouts to collect next/);
  assert.match(visualQaSource, /adminv4-final-matches\.png/);
  assert.match(visualQaSource, /Test Mode rewind before QM3/);
  assert.match(visualQaSource, /Next Known Match\\s\+QM3/);
  assert.match(visualQaSource, /impossiblePercentPattern/);
  assert.match(visualQaSource, /adminv4-final-settings\.png/);
  assert.match(visualQaSource, /stored only in this browser on this device/);
  assert.match(visualQaSource, /Local Credential Danger Zone/);
  assert.match(visualQaSource, /Next Best Action/);
  assert.match(visualQaSource, /Match-Day Trust/);
  assert.match(visualQaSource, /Required Action/);
  assert.match(visualQaSource, /fixture=test-mode/);
  assert.match(visualQaSource, /High model trust/);
  assert.match(visualQaSource, /Fallback Only/);
  assert.match(visualQaSource, /Official source cache is missing/);
  assert.match(visualQaSource, /Strategy Brain/);
  assert.match(visualQaSource, /Scout Ops/);
  assert.doesNotMatch(visualQaSource, /select\[aria-label="Admin workflow"\]/);
  assert.match(e2eSource, /impossiblePercentPattern/);
  assert.match(e2eSource, /selected cutoff match as future/);
  assert.match(e2eSource, /Next Known Match\\s\*QM3/);
});

test('scout-facing screens keep model and offline export details deliberate', () => {
  const scoutHeaderSource = readFileSync('src/components/scouting/ScoutWorkflowHeader.tsx', 'utf8');
  const matchScoutSource = readFileSync('src/views/MatchScoutV4View.tsx', 'utf8');
  const qrSource = readFileSync('src/views/QRScannerView.tsx', 'utf8');
  const setupSource = readFileSync('src/views/SetupView.tsx', 'utf8');
  const missionPanelSource = readFileSync('src/components/scouting/ScoutingMissionPanel.tsx', 'utf8');
  const historySource = readFileSync('src/views/HistoryView.tsx', 'utf8');
  const usernameGateSource = readFileSync('src/components/ScoutUsernameGate.tsx', 'utf8');
  const scoutArchiveSource = readFileSync('src/utils/scoutArchive.ts', 'utf8');
  const scoutIdentityLockSource = readFileSync('src/utils/scoutIdentityLock.ts', 'utf8');
  const preMatchSource = readFileSync('src/views/PreMatchView.tsx', 'utf8');
  const defenseScoutSource = readFileSync('src/views/MatchDefenseScoutView.tsx', 'utf8');
  const appSource = readFileSync('src/App.tsx', 'utf8');
  const workflowSource = readFileSync('src/utils/scoutingWorkflow.ts', 'utf8');
  const handoffSource = readFileSync('src/utils/scoutTaskHandoff.ts', 'utf8');
  const pitSource = readFileSync('src/views/PitScoutView.tsx', 'utf8');

  assert.match(scoutHeaderSource, /Scout Task/);
  assert.match(scoutHeaderSource, /Open task context/);
  assert.match(scoutHeaderSource, /Advanced range and model context/);
  assert.match(scoutHeaderSource, /Task Evidence Brief/);
  assert.match(scoutHeaderSource, /Submit clean evidence first/);
  assert.match(scoutHeaderSource, /Open admin-use details/);
  assert.match(scoutHeaderSource, /Needs role evidence/);
  assert.match(scoutHeaderSource, /Needs risk read/);
  assert.doesNotMatch(scoutHeaderSource, /Used Next/);
  assert.doesNotMatch(scoutHeaderSource, /handoff\.ppa\.role \|\| 'Unknown'/);
  assert.doesNotMatch(scoutHeaderSource, /This row becomes decision fuel/);
  assert.doesNotMatch(scoutHeaderSource, /PPA Evidence Brief/);
  assert.doesNotMatch(scoutHeaderSource, /getAdminUseMomentRoute/);
  assert.doesNotMatch(scoutHeaderSource, /Open Data Workflow/);
  assert.match(matchScoutSource, /Offline QR/);
  assert.match(matchScoutSource, /Offline Backup/);
  assert.match(matchScoutSource, /Use this only when Firebase sync is not available/);
  assert.match(matchScoutSource, /Evidence Capture Path/);
  assert.doesNotMatch(matchScoutSource, /PPA Capture Path/);
  assert.match(matchScoutSource, /verifyScoutIdentityUnlockPassphrase/);
  assert.match(matchScoutSource, /renameScoutArchiveUsername/);
  assert.match(matchScoutSource, /Change With Admin Passphrase/);
  assert.match(matchScoutSource, /Confirm Reset/);
  assert.match(matchScoutSource, /within 3 seconds/);
  assert.doesNotMatch(matchScoutSource, /Reset \$\{label\} to 0/);
  assert.doesNotMatch(matchScoutSource, /powerCoinPanelOpen/);
  assert.doesNotMatch(matchScoutSource, /handleBetSubmit/);
  assert.doesNotMatch(matchScoutSource, /Scout rewards are optional/);
  assert.doesNotMatch(matchScoutSource, /side incentive, not part of the match evidence/);
  assert.doesNotMatch(matchScoutSource, /Lock Prediction/);
  assert.doesNotMatch(matchScoutSource, /Open Prediction/);
  assert.match(usernameGateSource, /Change locked scout identity/);
  assert.match(usernameGateSource, /Admin Unlock Passphrase/);
  assert.match(usernameGateSource, /Unlock And Rename Device/);
  assert.match(scoutArchiveSource, /Scout identity is locked on this device/);
  assert.match(scoutArchiveSource, /USERNAME_RENAME_HISTORY_KEY/);
  assert.match(scoutIdentityLockSource, /verifyScoutIdentityUnlockPassphrase/);
  assert.doesNotMatch(scoutIdentityLockSource, /leoscout/);
  assert.match(missionPanelSource, /Open expected-range checklist/);
  assert.match(missionPanelSource, /Where this evidence goes/);
  assert.match(missionPanelSource, /Expected Range Needs/);
  assert.match(missionPanelSource, /EXPECTED_RANGE_COLLECTION_FIELDS/);
  assert.doesNotMatch(missionPanelSource, /Model safety checks|PPA safety checks|PPA Needs/);
  assert.match(historySource, /Expected Range Evidence/);
  assert.match(historySource, /Public-only context/);
  assert.match(historySource, /Expected Floor \/ Exp \/ Ceiling/);
  assert.match(historySource, /Scout name missing/);
  assert.match(historySource, /Needs role evidence/);
  assert.match(historySource, /Needs risk read/);
  assert.doesNotMatch(historySource, /Unknown Scout/);
  assert.match(historySource, /Privacy Review/);
  assert.match(historySource, /Export Device Evidence JSON/);
  assert.match(historySource, /Export Compact Summary/);
  assert.match(historySource, /containsScoutNames: false/);
  assert.match(historySource, /deleted tombstones/);
  assert.match(historySource, /Delete Review/);
  assert.match(historySource, /Move Evidence Row To Tombstones/);
  assert.match(historySource, /recordPendingDelete/);
  assert.doesNotMatch(historySource, /window\.confirm/);
  assert.doesNotMatch(historySource, /PPA Shape Evidence|Admin V4 uses for PPA|PPA Floor \/ Exp \/ Ceiling/);
  assert.match(setupSource, /Where this evidence goes/);
  assert.match(setupSource, /Decision Signals/);
  assert.match(setupSource, /Capture the evidence that explains whether this expected range is trustworthy/);
  assert.match(setupSource, /Needs role evidence/);
  assert.match(setupSource, /Needs tail read/);
  assert.doesNotMatch(setupSource, /pendingTask\.ppa\.role \|\| 'Unknown'/);
  assert.doesNotMatch(setupSource, /PROMOTED_PPA_MODEL|PPA_SHAPE_OUTPUTS|How admins use this evidence|Decision Model|Capture the evidence that explains whether this PPA shape is trustworthy/);
  assert.match(workflowSource, /EXPECTED_RANGE_OUTPUTS/);
  assert.doesNotMatch(workflowSource, /PPA_SHAPE_OUTPUTS/);
  assert.match(usernameGateSource, /expected ranges/);
  assert.doesNotMatch(usernameGateSource, /supports PPA/);
  assert.match(matchScoutSource, /central expected range/);
  assert.doesNotMatch(matchScoutSource, /central PPA estimate|expected-value part of PPA|Tell PPA why/);
  assert.match(preMatchSource, /Range Guardrail/);
  assert.match(preMatchSource, /Public Context/);
  assert.match(preMatchSource, /first starting read/);
  assert.match(preMatchSource, /final expected range/);
  assert.doesNotMatch(preMatchSource, /PPA Guardrail|final PPA|tells PPA|public fallback|Public Fallback|first fallback/);
  assert.match(defenseScoutSource, /Defense Evidence Map/);
  assert.match(defenseScoutSource, /Role Guard/);
  assert.doesNotMatch(defenseScoutSource, /Defense PPA Evidence Map|PPA Role Guard|Protects PPA|No PPA role correction/);
  assert.match(appSource, /Evidence To Match Strategy/);
  assert.doesNotMatch(appSource, /Evidence To PPA To Strategy/);
  assert.match(workflowSource, /expected range, downside risk/);
  assert.match(workflowSource, /EXPECTED_RANGE_COLLECTION_FIELDS/);
  assert.doesNotMatch(workflowSource, /PPA_COLLECTION_FIELDS|PPA expected range|strongest local signal for PPA|protects PPA from role confusion/);
  assert.match(pitSource, /early expected-range prior/);
  assert.match(pitSource, /public-only context/);
  assert.match(pitSource, /not the final expected range/);
  assert.match(pitSource, /Scout name missing/);
  assert.doesNotMatch(pitSource, /Unknown Scout/);
  assert.doesNotMatch(pitSource, /early PPA capability prior|not final PPA|early PPA prior/);
  assert.doesNotMatch([historySource, pitSource, workflowSource, handoffSource].join('\n'), /public\/model fallback|Public fallback context|model fallback context/);
  assert.match(setupSource, /canShowAdminTools/);
  assert.match(setupSource, /isCurrentUserAdmin/);
  assert.match(qrSource, /Scan \/ Upload/);
  assert.match(qrSource, /Review Issues/);
  assert.match(qrSource, /Sync Trusted Rows/);
  assert.match(qrSource, /Scout name missing/);
  assert.match(qrSource, /Team name missing/);
  assert.match(qrSource, /Needs role evidence/);
  assert.match(qrSource, /Needs tail read/);
  assert.match(qrSource, /selectedIntakeStep/);
  assert.match(qrSource, /setSelectedIntakeStep\(step\.key\)/);
  assert.match(qrSource, /showScanStep/);
  assert.match(qrSource, /showReviewStep/);
  assert.match(qrSource, /showSyncStep/);
  assert.match(qrSource, /h-10 w-10/);
  assert.match(qrSource, /Remove failed QR image/);
  assert.match(qrSource, /usable strategy evidence/);
  assert.match(qrSource, /Expected range \{ppaRange/);
  assert.doesNotMatch(qrSource, /usable PPA evidence|PPA \{ppaRange|Protects PPA|stronger for PPA/);
  assert.match(qrSource, /aria-label="Remove staged evidence row"/);
  [qrSource, matchScoutSource, preMatchSource, defenseScoutSource, pitSource, setupSource, historySource].forEach(source => {
    assert.doesNotMatch(source, /bg-gradient|shadow-xl|shadow-2xl|shadow-emerald-900|shadow-cyan-900|shadow-violet-950/);
  });
});
